version: '3'

# docker-compose up
# docker rm $(docker ps -a -q) && docker volume prune -f

services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "love"
      MYSQL_DATABASE: golang
    ports:
      - '3306:3306'
    volumes:
      - './_sql/:/docker-entrypoint-initdb.d/'
  
  mongodb:
    image: 'mongo:5'
    environment:
      - MONGO_INITDB_DATABASE=coursera
    ports:
      - '27017-27019:27017-27019'

  redditclone:
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: sh -c ./entrypoint.sh
    ports:
      - 8080:8080
    env_file:
      .env
    expose:
      - 8080
    depends_on:
      - mysql
      - mongodb
    restart: unless-stopped